<a href="https://colab.research.google.com/github/naomileon/-th-digraph-in-Dublin/blob/main/ChiSquareGenderCulture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from scipy.stats import chi2_contingency

task1 = np.array([
    [90, 38, 9],   # Femme Proche
    [71, 48, 18],  # Homme Proche
    [50, 73, 13],  # Femme Éloignée
    [80, 46, 11]   # Homme Éloigné
])

task2 = np.array([
    [42, 27, 1],   # Femme Proche
    [21, 34, 3],   # Homme Proche
    [19, 41, 1],   # Femme Éloignée
    [23, 21, 5]    # Homme Éloigné
])

combined = task1 + task2

F_close = combined[0]
F_far = combined[2]
M_close = combined[1]
M_far = combined[3]

def test_chi2(table, task_name):
    chi2, p, dof, expected = chi2_contingency(table)
    print(f"\nResults for {task_name}:")
    print("Chi² =", round(chi2, 3))
    print("p-value =", round(p, 4))
    print("Degree of Freedom =", dof)
    print("Expected frequences =\n", np.round(expected, 2))
    if p < 0.05:
        print("=> There is a significant correlation between the group culture+gender and pronunciation..")
    else:
        print("=> No significant correlation detected between the group culture+gender and pronunciation.")


test_chi2(task1, "Task 1")
test_chi2(task2, "Task 2")
test_chi2(combined, "All Tasks")

test_chi2(np.array([F_close, F_far]), "Women : Close vs Far")
test_chi2(np.array([M_close, M_far]), "Men : Close vs Far")



Results for Task 1:
Chi² = 28.941
p-value = 0.0001
Degree of Freedom = 6
Expected frequences =
 [[72.88 51.34 12.77]
 [72.88 51.34 12.77]
 [72.35 50.97 12.68]
 [72.88 51.34 12.77]]
=> There is a significant correlation between the group culture+gender and pronunciation..

Results for Task 2:
Chi² = 20.26
p-value = 0.0025
Degree of Freedom = 6
Expected frequences =
 [[30.88 36.18  2.94]
 [25.59 29.97  2.44]
 [26.91 31.53  2.56]
 [21.62 25.32  2.06]]
=> There is a significant correlation between the group culture+gender and pronunciation..

Results for All Tasks:
Chi² = 41.733
p-value = 0.0
Degree of Freedom = 6
Expected frequences =
 [[104.42  86.49  16.09]
 [ 98.37  81.48  15.15]
 [ 99.38  82.31  15.31]
 [ 93.83  77.72  14.45]]
=> There is a significant correlation between the group culture+gender and pronunciation..

Results for Women : Close vs Far:
Chi² = 33.599
p-value = 0.0
Degree of Freedom = 2
Expected frequences =
 [[102.99  91.72  12.3 ]
 [ 98.01  87.28  11.7 ]]
=> There is a