<a href="https://colab.research.google.com/github/naomileon/-th-digraph-in-Dublin/blob/main/ChiSquareGender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from scipy.stats import chi2_contingency

# Données Task 1
# Lignes : Women, Men ; Colonnes : FR, OCC, ?
task1 = np.array([
    [140, 111, 22],
    [151,  94, 29]
])

# Données Task 2
task2 = np.array([
    [61, 68, 2],
    [44, 55, 8]
])

combined = task1 + task2

def test_chi2(table, task_name):
    chi2, p, dof, expected = chi2_contingency(table)
    print(f"\nResults for {task_name}:")
    print("Chi² =", chi2)
    print("p-value =", p)
    print("Degree of freedom =", dof)
    print("Expected frequencies =\n", expected)
    if p < 0.05:
        print("=> There is a significant correlation between gender and pronunciation.")
    else:
        print("=> No significant correlation detected between gender and pronunciation.")

test_chi2(task1, "Task 1")
test_chi2(task2, "Task 2")
test_chi2(combined, "All Tasks")


Results for Task 1:
Chi² = 2.784529124160384
p-value = 0.24851189631901177
Degree of freedom = 2
Expected frequencies =
 [[145.23400366 102.31261426  25.45338208]
 [145.76599634 102.68738574  25.54661792]]
=> No significant correlation detected between gender and pronunciation.

Results for Task 2:
Chi² = 5.36070845448413
p-value = 0.06853887151831407
Degree of freedom = 2
Expected frequencies =
 [[57.79411765 67.70168067  5.50420168]
 [47.20588235 55.29831933  4.49579832]]
=> No significant correlation detected between gender and pronunciation.

Results for All Tasks:
Chi² = 4.935655009141964
p-value = 0.08476881897485676
Degree of freedom = 2
Expected frequencies =
 [[203.80127389 168.80509554  31.39363057]
 [192.19872611 159.19490446  29.60636943]]
=> No significant correlation detected between gender and pronunciation.
