<a href="https://colab.research.google.com/github/naomileon/-th-digraph-in-Dublin/blob/main/ChiSquareCulture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from scipy.stats import chi2_contingency

# Données Task 1 : lignes = Proche, Éloigné ; colonnes = FR, OCC, ?
task1 = np.array([
    [161, 86, 27],
    [130, 119, 24]
])

# Données Task 2 (de même pour les lignes et colonnes)
task2 = np.array([
    [63, 61, 4],
    [42, 62, 6]
])

# Pour avoir une vue plus générale
combined = task1 + task2

def test_chi2(table, task_name):
    chi2, p, dof, expected = chi2_contingency(table)
    print(f"\nResults for {task_name}:")
    print("Chi² =", chi2)
    print("p-value =", p)
    print("Degree of Freedom =", dof)
    print("Expected frequences =\n", expected)
    if p < 0.05:
        print("=> There is a significant correlation between culture and pronunciation.")
    else:
        print("=> No significant correlation detected between culture and pronunciation.")

# Exécution des tests
test_chi2(task1, "Task 1")
test_chi2(task2, "Task 2")
test_chi2(combined, "All Tasks")



Results for Task 1:
Chi² = 8.78927242993032
p-value = 0.012343369841999564
Degree of Freedom = 2
Expected frequences =
 [[145.76599634 102.68738574  25.54661792]
 [145.23400366 102.31261426  25.45338208]]
=> There is a significant correlation between culture and pronunciation.

Results for Task 2:
Chi² = 3.2654637841832983
p-value = 0.19539504614166198
Degree of Freedom = 2
Expected frequences =
 [[56.47058824 66.1512605   5.37815126]
 [48.52941176 56.8487395   4.62184874]]
=> No significant correlation detected between culture and pronunciation.

Results for All Tasks:
Chi² = 9.915002359429502
p-value = 0.007030473791882085
Degree of Freedom = 2
Expected frequences =
 [[202.79235669 167.96942675  31.23821656]
 [193.20764331 160.03057325  29.76178344]]
=> There is a significant correlation between culture and pronunciation.
